---
- name: Health Check, Consolidated HTML Table, Email Report
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Check if instance is OCI (by cloud agent)
      stat:
        path: /etc/oracle-cloud-agent
      register: oci_agent
      
    - name: Set server_type variable
      set_fact:
        server_type: "{{ 'OCI Cloud Instance' if oci_agent.stat.exists else 'On-Premise Server' }}"

    - name: Set OS info
      set_fact:
        os_version: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Set server uptime in days
      set_fact:
        uptime_days: "{{ (ansible_uptime_seconds // 86400) | int }}"
        
    - name: Get free root space in GB
      set_fact:
        free_root_gb: "{{ (ansible_mounts | selectattr('mount', 'equalto', '/') | first).size_available // (1024**3) }}"
 
    - name: Get free root space in percentage
      shell: "df -hT / | awk 'NR==2 {print $6}'"
      register: root_available_out
        
    - name: Clean up the value "root_available_out"
      set_fact:
        root_available: "{{ root_available_out.stdout | trim }}"

        
    - name: Build HTML row for the host
      set_fact:
        html_content: >-
          <tr>
            <td>{{ ansible_hostname }}</td>
            <td>{{ server_type }}</td>
            <td>{{ os_version }}</td>
            <td>{{ uptime_days }}</td>
            <td>{{ free_root_gb }}</td>
            <td>{{ root_available }}</td>
          </tr>

- name: Email consolidated report
  hosts: localhost
  gather_facts: false
  vars:
    mail_subject: "Server Health Check Report_{{ lookup('pipe','date +%Y-%m-%d') }}"
  tasks:
    - name: Send health check HTML mail
      mail:
        host: iadpaimrmta01.imrmtpd1.prodappiadaev1.oraclevcn.com                  # e.g., smtp.yourdomain.com
        port: 25
        to: vinodkumar.vv@oracle.com                                               # e.g., your.email@oracle.com
        from: olam.test@oracle.com
        subject: "{{ mail_subject }}"
        charset: utf-8
        subtype: html
        body: |
          <!DOCTYPE html>
          <html>
          <head>
          <style>
          body {font-family: arial; font-size: 90%; color: black;}
          table, th, td {border: 1px solid black; padding: 4px; border-collapse:collapse;}
          table {width: auto !important; white-space: nowrap; text-align:center;}
          th {color: black; background-color: cyan; border-color:black;}
          td {font-family: courier; font-size: 100%; background-color: azure;}
          </style>
          </head>
          <body>
          <p>Hello Team,</p>
          <p>Please find the report below:</p>
          <table>
          <tr><th>Host Name</th><th>Server Type</th><th>OS</th><th>Server Uptime (Days)</th><th>Free Space in / (GB)</th><th>Available Space in / (%)</th></tr>
          {% for i in groups['all'] %}
            {{ hostvars[i]['html_content']|d('<tr><td>' + i + '</td><td colspan=8><span style=color:red>Server Unreachable</span></td></tr>') }}
          {% endfor %}
          </table>
          <p>Thanks & Regards,<br>UNIX Team</p>
          </body>
          </html>
      delegate_to: localhost
      run_once: true
